openapi: 3.0.0
info:
  title: Drone API
  description: API documentation for the Drone project
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /api/positions:
    get:
      summary: Retrieve the latest drone positions
      responses:
        '200':
          description: A list of recent drone positions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    droneId:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
                    name:
                      type: string
  /api/drone/{droneId}:
    get:
      summary: Retrieve a specific drone's details
      parameters:
        - in: path
          name: droneId
          schema:
            type: string
          required: true
          description: The ID of the drone to retrieve
      responses:
        '200':
          description: Detailed information of the specified drone
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  sender_id:
                    type: string
                  drone:
                    type: object
                    properties:
                      name:
                        type: string
                      frequency:
                        type: integer
                      bandwidth:
                        type: integer
                      allow_track:
                        type: boolean
                      allow_takeover:
                        type: boolean
                      class_name:
                        type: string
                      radio_resources:
                        type: integer
                      droneId:
                        type: string
                      latitude:
                        type: number
                        format: float
                      longitude:
                        type: number
                        format: float
        '404':
          description: Drone not found
        '500':
          description: Internal Server Error
  /api/marks:
    get:
      summary: Retrieve the latest sensor marks
      responses:
        '200':
          description: A list of recent sensor marks
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  lat:
                    type: number
                  lon:
                    type: number
                  state:
                    type: boolean
        '404':
          description: No sensor data available
        '500':
          description: Internal Server Error
  /api/drone/control:
    post:
      summary: Control a drone by sending commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                droneId:
                  type: string
                enum:
                  type: string
                command:
                  type: string
              required:
                - droneId
                - enum
                - command
      responses:
        '200':
          description: Command processed successfully
        '400':
          description: Missing required fields
        '500':
          description: Internal Server Error
  /api/dronelist:
    get:
      summary: Retrieve the list of all drones
      responses:
        '200':
          description: A list of all available drones
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    droneId:
                      type: string
                    name:
                      type: string
                    createdAt:
                      type: string
                      format: date-time
        '500':
          description: Internal Server Error
    delete:
      summary: Delete all drones from the list
      responses:
        '200':
          description: All drones deleted successfully
        '500':
          description: Internal Server Error
  /api/sensorlist:
    get:
      summary: Retrieve the list of all sensors
      responses:
        '200':
          description: A list of all available sensors
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sensor_id:
                      type: string
                    latitude:
                      type: number
                    longitude:
                      type: number
                    radius:
                      type: number
        '404':
          description: No sensor data available
        '500':
          description: Internal Server Error
  /api/sensor/{sensor_id}:
    delete:
      summary: Delete a specific sensor by ID
      parameters:
        - in: path
          name: sensor_id
          schema:
            type: string
          required: true
          description: The ID of the sensor to delete
      responses:
        '200':
          description: Sensor deleted successfully
        '404':
          description: Sensor not found
        '500':
          description: Internal Server Error
    put:
      summary: Update the radius of a specific sensor
      parameters:
        - in: path
          name: sensor_id
          schema:
            type: string
          required: true
          description: The ID of the sensor to update
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                radius:
                  type: number
      responses:
        '200':
          description: Radius updated successfully
        '400':
          description: Invalid radius value
        '404':
          description: Sensor not found
        '500':
          description: Internal Server Error
  /api/login:
    post:
      summary: Log in with user credentials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                password:
                  type: string
              required:
                - id
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Invalid password
        '404':
          description: User not found
        '500':
          description: Internal Server Error
